language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ethancollins/ansible-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true ethancollins/ansible-frontend npm run test

after_success:
    - docker build -t ethancollins/ansible-frontend .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push ethancollins/ansible-frontend